Repository vapor/jwt-kit, pull requests merged in 2020-07, with the labels that each got.

#33 Improve CI
  .github/workflows/test.yml
Labels: enhancement

#32 Add support for Apple Silicon
  Package.swift
  Sources/CJWTKitBoringSSL/crypto/chacha/chacha-armv4.ios.arm.S
  Sources/CJWTKitBoringSSL/crypto/chacha/chacha-armv8.ios.aarch64.S
  Sources/CJWTKitBoringSSL/crypto/fipsmodule/aesv8-armx32.ios.arm.S
  Sources/CJWTKitBoringSSL/crypto/fipsmodule/aesv8-armx64.ios.aarch64.S
  Sources/CJWTKitBoringSSL/crypto/fipsmodule/armv4-mont.ios.arm.S
  Sources/CJWTKitBoringSSL/crypto/fipsmodule/armv8-mont.ios.aarch64.S
  Sources/CJWTKitBoringSSL/crypto/fipsmodule/bsaes-armv7.ios.arm.S
  Sources/CJWTKitBoringSSL/crypto/fipsmodule/ghash-armv4.ios.arm.S
  Sources/CJWTKitBoringSSL/crypto/fipsmodule/ghash-neon-armv8.ios.aarch64.S
  Sources/CJWTKitBoringSSL/crypto/fipsmodule/ghashv8-armx32.ios.arm.S
  Sources/CJWTKitBoringSSL/crypto/fipsmodule/ghashv8-armx64.ios.aarch64.S
  Sources/CJWTKitBoringSSL/crypto/fipsmodule/sha1-armv4-large.ios.arm.S
  Sources/CJWTKitBoringSSL/crypto/fipsmodule/sha1-armv8.ios.aarch64.S
  Sources/CJWTKitBoringSSL/crypto/fipsmodule/sha256-armv4.ios.arm.S
  Sources/CJWTKitBoringSSL/crypto/fipsmodule/sha256-armv8.ios.aarch64.S
  Sources/CJWTKitBoringSSL/crypto/fipsmodule/sha512-armv4.ios.arm.S
  Sources/CJWTKitBoringSSL/crypto/fipsmodule/sha512-armv8.ios.aarch64.S
  Sources/CJWTKitBoringSSL/crypto/fipsmodule/vpaes-armv7.ios.arm.S
  Sources/CJWTKitBoringSSL/crypto/fipsmodule/vpaes-armv8.ios.aarch64.S
  Sources/CJWTKitBoringSSL/hash.txt
  scripts/build-asm.py
  scripts/vendor-boringssl.sh
Labels: enhancement, semver-minor

#34 Support JWKs with no algorithm
  Sources/JWTKit/Keys/JWK.swift
  Sources/JWTKit/Signing/JWKSigner.swift
  Sources/JWTKit/Signing/JWTSigner+JWK.swift
  Sources/JWTKit/Signing/JWTSigner.swift
  Sources/JWTKit/Signing/JWTSigners.swift
  Tests/JWTKitTests/JWTKitTests.swift
Labels: enhancement, semver-major

#36 Add support for Microsoft JWTs
  Sources/JWTKit/MicrosoftIdentitiyToken.swift
Labels: enhancement, semver-minor

#37 JWTKit 4.0.0
  .github/FUNDING.yml
  .github/contributing.md
  LICENSE
  README.md
  Sources/JWTKit/ECDSA/ECDSAError.swift
  Sources/JWTKit/ECDSA/ECDSAKey.swift
  Sources/JWTKit/ECDSA/ECDSASigner.swift
  Sources/JWTKit/ECDSA/JWTSigner+ECDSA.swift
  Sources/JWTKit/HMAC/HMACError.swift
  Sources/JWTKit/HMAC/HMACSigner.swift
  Sources/JWTKit/HMAC/JWTSigner+HMAC.swift
  Sources/JWTKit/JWK/JWK.swift
  Sources/JWTKit/JWK/JWKIdentifier.swift
  Sources/JWTKit/JWK/JWKS.swift
  Sources/JWTKit/JWTSigner.swift
  Sources/JWTKit/JWTSigners.swift
  Sources/JWTKit/RSA/JWTSigner+RSA.swift
  Sources/JWTKit/RSA/RSAError.swift
  Sources/JWTKit/RSA/RSAKey.swift
  Sources/JWTKit/RSA/RSASigner.swift
  Sources/JWTKit/Signing/JWKSigner.swift
  Sources/JWTKit/Utilities/Base64URL.swift
  Sources/JWTKit/Utilities/Exports.swift
  Sources/JWTKit/Utilities/OpenSSLSigner.swift
  Sources/JWTKit/Utilities/Utilities.swift
  Sources/JWTKit/Vendor/AppleIdentityToken.swift
  Sources/JWTKit/Vendor/GoogleIdentityToken.swift
  Sources/JWTKit/Vendor/MicrosoftIdentitiyToken.swift
  Tests/JWTKitTests/JWTKitTests.swift
  Tests/LinuxMain.swift
Labels: enhancement, release

#39 Set default signer when using JWKs
  Sources/JWTKit/JWTSigners.swift
  Tests/JWTKitTests/JWTKitTests.swift
Labels: bug, semver-patch
