Repository vapor/jwt-kit, pull requests merged in 2020-02, with the labels that each got.

#10 JWKS.find
  Sources/JWTKit/JWK.swift
Labels: enhancement, semver-minor

#11 Apple/Google identity tokens
  Sources/JWTKit/AppleIdentityToken.swift
  Sources/JWTKit/Claims/AudienceClaim.swift
  Sources/JWTKit/Claims/BoolClaim.swift
  Sources/JWTKit/Claims/ExpirationClaim.swift
  Sources/JWTKit/Claims/GoogleHostedDomainClaim.swift
  Sources/JWTKit/Claims/IDClaim.swift
  Sources/JWTKit/Claims/IssuedAtClaim.swift
  Sources/JWTKit/Claims/IssuerClaim.swift
  Sources/JWTKit/Claims/JWTClaim.swift
  Sources/JWTKit/Claims/JWTUnixEpochClaim.swift
  Sources/JWTKit/Claims/LocaleClaim.swift
  Sources/JWTKit/Claims/NotBeforeClaim.swift
  Sources/JWTKit/Claims/SubjectClaim.swift
  Sources/JWTKit/GoogleIdentityToken.swift
  Sources/JWTKit/JWTClaims.swift
  Sources/JWTKit/JWTError.swift
  Sources/JWTKit/JWTSigner+RSA.swift
  Sources/JWTKit/Keys/JWK.swift
  Sources/JWTKit/Keys/JWKIdentifier.swift
  Sources/JWTKit/Keys/JWKS.swift
  Sources/JWTKit/Signing/ECDSA/ECDSAError.swift
  Sources/JWTKit/Signing/ECDSA/ECDSAKey.swift
  Sources/JWTKit/Signing/ECDSA/ECDSASigner.swift
  Sources/JWTKit/Signing/ECDSA/JWTSigner+ECDSA.swift
  Sources/JWTKit/Signing/HMAC/HMACError.swift
  Sources/JWTKit/Signing/HMAC/HMACSigner.swift
  Sources/JWTKit/Signing/HMAC/JWTSigner+HMAC.swift
  Sources/JWTKit/Signing/JWTSigner+JWK.swift
  Sources/JWTKit/Signing/JWTSigner.swift
  Sources/JWTKit/Signing/JWTSigners.swift
  Sources/JWTKit/Signing/OpenSSLSigner.swift
  Sources/JWTKit/Signing/RSA/JWTSigner+RSA.swift
  Sources/JWTKit/Signing/RSA/RSAError.swift
  Sources/JWTKit/Signing/RSA/RSAKey.swift
  Sources/JWTKit/Signing/RSA/RSASigner.swift
Labels: enhancement, semver-minor

#12 BoolClaim handles strings
  Sources/JWTKit/Claims/BoolClaim.swift
  Sources/JWTKit/JWTError.swift
  Tests/JWTKitTests/JWTKitTests.swift
Labels: enhancement, semver-patch

#14 Remove OpenSSL
  Package.swift
  Sources/CJWTKitCrypto/c_jwtkit_crypto.c
  Sources/CJWTKitCrypto/include/c_jwtkit_crypto.h
  Sources/CJWTKitOpenSSL/module.modulemap
  Sources/JWTKit/Signing/ECDSA/ECDSAKey.swift
  Sources/JWTKit/Signing/ECDSA/ECDSASigner.swift
  Sources/JWTKit/Signing/ECDSA/JWTSigner+ECDSA.swift
  Sources/JWTKit/Signing/HMAC/HMACSigner.swift
  Sources/JWTKit/Signing/HMAC/JWTSigner+HMAC.swift
  Sources/JWTKit/Signing/OpenSSLSigner.swift
  Sources/JWTKit/Signing/RSA/JWTSigner+RSA.swift
  Sources/JWTKit/Signing/RSA/RSAKey.swift
  Sources/JWTKit/Signing/RSA/RSASigner.swift
  Sources/JWTKit/Utilities.swift
Labels: enhancement, semver-major

#7 Fix ECDSA signature size
  Sources/JWTKit/Signing/ECDSA/ECDSAKey.swift
  Sources/JWTKit/Signing/ECDSA/ECDSASigner.swift
Labels: bug, semver-minor

#17 Fixes Codable support for LocaleClaim
  Sources/JWTKit/Claims/LocaleClaim.swift
  Tests/JWTKitTests/JWTKitTests.swift
Labels: bug, semver-patch

#15 Add Swift Crypto as a dependency
  Package.swift
Labels: enhancement

#16 Swift Crypto HMAC integration
  Sources/JWTKit/Signing/HMAC/HMACSigner.swift
  Sources/JWTKit/Signing/HMAC/JWTSigner+HMAC.swift
Labels: enhancement

#18 Release Candidate 1
  .github/workflows/test.yml
  Package.swift
  README.md
Labels: enhancement
